[profile.default]

src = 'src'
test = 'test'
libs = ['lib']

out = '../build/periphery'
cache_path = '../cache/periphery'

optimizer = true
optimizer_runs = 800
gas_reports = []

auto_detect_remappings = true
remappings = [
    'forge-std/=lib/core/lib/forge-std/src',

    'clones-with-immutable-args/=lib/core/lib/clones-with-immutable-args/src',
    'openzeppelin-contracts/=lib/core/lib/openzeppelin-contracts/contracts/',
    'solmate/=lib/core/lib/solmate/src/',
    'v3-core/=lib/core/lib/v3-core/',

    'aloe-ii-core/=lib/core/src/'
]

allow_paths = [
    '../core'
]
